title: AI primer
description: Mainly used for AI primer higlights. If you want to know more about me see my [linkedin](https://www.linkedin.com/in/tamosiunasrokas/) profile.
theme: jekyll-theme-minimal
